config/routes.rb
Rails.application.routes.draw do
  # get 'users/show'
  # get 'users/edit'
  get 'home/about' => 'homes#about'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root "devise/sessions#new"
  root "homes#top"
  resources :users, only: [:index, :create, :show, :edit, :update]
  resources :books, only: [:index, :new, :create, :show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, length:{in:2..20}
  validates :introduction, length:{maximum: 50}
  has_many :books, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	def after_sign_up_path_for(resource)
		"/users/#{current_user.id}"#ログイン後に移動するpath
		# flash[:signedup] ="Welcome! You have signed up successfully."
	end

	def after_sign_in_path_for(resource)
		"/users/#{current_user.id}"#ログイン後に移動するpath
		# flash[:signedin] ="Signed in successfully."
	end



	protected
	def configure_permitted_parameters
		#devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
		devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!
def index
	@books = Book.all
	# @books = Book.page(params[:page]).reverse_order
	@book = Book.new
	@user = current_user
end
def new
	@book = Book.new
end
def create
	@book = Book.new(book_params)
	@book.user_id = current_user.id
	if @book.save
		redirect_to book_path(@book)
		flash[:create] = "You have created book successfully."
	else
		@books = Book.page(params[:page]).reverse_order
		render :index
	end
end
def show
	@book = Book.find(params[:id])
	@book1  = Book.new
end
def edit
	@book = Book.find(params[:id])
	if current_user.id == @book.user.id
	else
	redirect_to books_path
	end
end
def update
	@book = Book.find(params[:id])
	if @book.update(book_params)
	flash[:update] = "You have updated book successfully."
	redirect_to book_path(@book)
	else
	render :edit
	end
end

def destroy
	@book = Book.find(params[:id])
	@book.destroy
	redirect_to books_path
end

private
	def book_params
	params.require(:book).permit(:title, :body)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.page(params[:page]).reverse_order
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if current_user.id == @user.id
  else
    redirect_to user_path(current_user.id)
  end
end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:update] = "You have updated user successfully."
    redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
private
	def user_params
	params.require(:user).permit(:name, :profile_image, :introduction)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="body-wrap">
    <div id="st-container" class="st-container">
        <div class="st-pusher">
            <div class="st-content">
                <div class="st-content-inner">
                    <section class="slice slice-lg sct-color-1">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-4 col-md-offset-4">
                                    <div class="form-user style-1 rounded has-shadow-1">
                                        <div class="form-header text-center">
                                            <h2 class="form-header-title">User info</h2>
                                        </div>
                                        <%= form_for(@book, url: books_path) do |f| %>
                                        <% if @book.errors.any? %>
                                        <h4>
                                            <%= "#{@book.errors.full_messages.count} error(s) prohibited this obj from being saved:" %>
                                        </h4>
                                        <div id="error_explanation">
                                            <ul>
                                                <% @book.errors.full_messages.each do |message| %>
                                                <li>
                                                    <%= message %>
                                                </li>
                                                <% end %>
                                            </ul>
                                        </div>
                                        <% end %>
                                        <% end %>
                                        <div class="form-body">
                                            <!-- ここにform_forを追加します -->
                                            <%= form_for(@book) do |f| %>
                                            <h1>Title</h1>
                                            <%= f.text_field :title %>
                                            <h1>Opinion</h1>
                                            <%= f.text_area :body %><br>
                                            <%= f.submit "Update Book", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
                                            <% end %>
                                        </div>
                                    </div>
                                </div>
                            </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/books/index.html.erb
<div class="container">
    <div class="row">
        <% if @book.errors.any? %>
        <h4>
            <%= "#{@book.errors.full_messages.count} error(s) prohibited this obj from being saved:" %>
        </h4>
        <div id="error_explanation">
            <ul>
                <% @book.errors.full_messages.each do |message| %>
                <li>
                    <%= message %>
                </li>
                <% end %>
            </ul>
        </div>
        <% end %>
        <div class="col-lg-4">
            <h1>User info</h1>
            <table class="table table-striped">
                <tr>
                    <%= attachment_image_tag current_user, :profile_image, :fill, 100,100, format: "jpeg", class: "pull-left profile-img", fallback: "no_image.jpg" %>
                </tr>
                <tr>
                    <td>name</td>
                    <td>
                        <%= current_user.name %>
                    </td>
                </tr>
                <tr>
                    <td>introduction</td>
                    <td>
                        <%= current_user.introduction %>
                    </td>
                </tr>
            </table>
            <%= link_to  edit_user_path(current_user.id), class: 'btn btn-default btn-block' do %>
            <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
            <% end %>
            <h1>New book</h1>
            <%= form_for(@book, url: books_path) do |f| %>
            <ul>
                <li>
                    <h4>Title</h4>
                    <%= f.text_field :title, :size =>"44" %>
                </li>
                <li>
                    <h4> Opinion</h4>
                    <%= f.text_area :body, :cols =>"47", :rows => "1" %>
                </li>
                <br>
                <li>
                    <%= f.submit "Create Book", class: "btn btn-primary btn-block" %>
                </li>
                <% end %>
            </ul>
        </div>
        <div class="col-lg-8">
            <h1>Books</h1>
            <table class="table table-striped">
                <thread>
                    <tr>
                        <th></th>
                        <th>Title</th>
                        <th>Opinion</th>
                    </tr>
                </thread>
                <tbody>
                    <% @books.each do |book| %>
                    <tr>
                        <td>
                            <%= link_to user_path(book.user.id) do %>
                            <%= attachment_image_tag book.user, :profile_image, :fill, 50,50, format: "jpeg", class: "pull-left profile-img", fallback: "no_image.jpg", :width => "40", :height => "40" %>
                            <% end %>
                        </td>
                        <td>
                            <%= link_to book.title, book_path(book.id) %>
                        </td>
                        <td>
                            <%= book.body %>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
            <%#<%= paginate @books, class: "paginate" %>
        </div>
    </div>
</div>

app/views/books/new.html.erb
<h2>User info</h2>

<h2>New book</h2>
<%= form_for(@book, url: books_path) do |f| %>
<% if @book.errors.any? %>
<div id="error_explanation">
    <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li>
            <%= message %>
        </li>
        <% end %>
    </ul>
</div>
<% end %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4> Opinion</h4>
<%= f.text_area :body %>
<%= f.submit "Create Book" %>
<% end %>

app/views/books/show.html.erb
<% flash[:update] %>
<% flash[:create] %>
<div class="container">
    <div class="row">
        <div class="col-lg-4">
            <h1>User info</h1>
            <table class="table table-striped">
                <tr>
                    <%= attachment_image_tag @book.user, :profile_image, :fill, 100,100, format: "jpeg", class: "pull-left profile-img", fallback: "no_image.jpg" %>
                </tr>
                <tr>
                    <td>name</td>
                    <td>
                        <%= @book.user.name %>
                    </td>
                </tr>
                <tr>
                    <td>introduction</td>
                    <td>
                        <%= @book.user.introduction %>
                    </td>
                </tr>
            </table>
            <% if @book.user == current_user %>
            <%= link_to  edit_user_path(current_user), class: 'btn btn-default btn-block' do %>
            <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
            <% end %>
            <% else %>
            <%= link_to  user_path(current_user), class: 'btn btn-default btn-block' do %>
            <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
            <% end %>
            <% end %>
            <h1>New book</h1>
            <%= form_for(@book, url: books_path) do |f| %>
            <% if @book.errors.any? %>
            <div id="error_explanation">
                <ul>
                    <% @book.errors.full_messages.each do |message| %>
                    <li>
                        <%= message %>
                    </li>
                    <% end %>
                </ul>
            </div>
            <% end %>
            <% end %>
            <%= form_for(@book1) do |f| %>
            <ul>
                <li>
                    <h4>Title</h4>
                    <%= f.text_field :title, :size =>"44" %>
                </li>
                <li>
                    <h4> Opinion</h4>
                    <%= f.text_area :body, :cols =>"47", :rows => "1" %>
                </li>
                <br>
                <li>
                    <%= f.submit "Create Book", class: "btn btn-primary btn-block" %>
                </li>
            </ul>
            <% end %>
        </div>
        <div class="col-lg-8">
            <h1>Book detail</h1>
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <td>
                            <%= link_to user_path(@book.user.id) do %>
                            <%= attachment_image_tag @book.user, :profile_image, :fill, 50,50, format: "jpeg", class: "pull-left profile-img", fallback: "no_image.jpg", :width => "40", :height => "40" %>
                            <br><br>
                            <%= @book.user.name %>
                            <% end %>
                        </td>
                        <td>
                            <%= @book.title %>
                        </td>
                        <td>
                            <%= @book.body %>
                        </td>
                        <td>
                            <% if @book.user == current_user %>
                            <%= link_to "Edit", edit_book_path(@book) %>
                            <% end %>
                        </td>
                        <td>
                            <% if @book.user == current_user %>
                            <%= link_to "Destroy", book_path(@book), method: :delete %>
                            <% end %>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/homes/about.html.erb
<h1>
	welcome to
	<span class="glyphicon glyphicon-book" aria-hidden="true"></span><<strong>Bookers !!</strong>
</h1>

app/views/homes/top.html.erb
<%= flash[:signedout] %>

<div class="container1">
<h1>
	welcome to
	<span class="glyphicon glyphicon-book" aria-hidden="true"></span><<strong>Bookers !!</strong>
</h1>
<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span><<strong>Bookers,</strong><br>
you can share and exchange your opinionsm inpressions, and<br>
emotions<br>
about various books!</p>

 <div class="actions">
    <%= link_to "Log in",  "/users/sign_in", class: "btn btn-primary" %>
     <%= link_to "Sign up",  "/users/sign_up", class: "btn btn-success" %>
  </div>
</div>

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
<%= content_tag(:div, value, class: "#{key}") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <header>
        <hgroup class="header">
            <div class="container">
                <!-- 箱を作る -->
                <p class="booker">Bookers</p>
                <div id="slidemenu">
                    <ul class="navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
                        <% if user_signed_in? %>
                        <li class="nav-list-item">
                            <span class="glyphicon glyphicon-home" aria-hidden="true">
                                <%= link_to "Home", user_path(current_user.id) %></span>
                        </li>
                        <li class="nav-list-item">
                            <span class="glyphicon glyphicon-user" aria-hidden="true">
                                <%= link_to 'Users', users_path %></span>
                        </li>
                        <li class="nav-list-item">
                            <span class="glyphicon glyphicon-book" aria-hidden="true">
                                <%= link_to 'Books', books_path %></span>
                        </li>
                        <li class="nav-list-item">
                            <span class="glyphicon glyphicon-log-out" aria-hidden="true">
                                <%= link_to "logout", destroy_user_session_path, method: :delete %></span>
                        </li>
                        <% else %>
                        <li class="nav-list-item">
                            <span class="glyphicon glyphicon-home" aria-hidden="true">
                                <%= link_to "Home", "/" %></span>
                        </li>
                        <li class="nav-list-item">
                            <span class="glyphicon glyphicon-link" aria-hidden="true">
                                <%= link_to "About", "/home/about" %></span>
                        </li>
                        <li class="nav-list-item">
                            <span class="glyphicon glyphicon-edit" aria-hidden="true">
                                <%= link_to "Sign up", new_user_registration_path %></span>
                        </li>
                        <li class="nav-list-item">
                            <span class="glyphicon glyphicon-log-in" aria-hidden="true">
                                <%= link_to "login", new_user_session_path %></span>
                        </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </hgroup>
    </header>
<!--     <div id="container">
        <div id="theTarget">
            <div class="image1"></div>
            <div class="image2"></div>
            <div class="image3"></div>
            <div class="image4"></div>
            <div class="image5"></div>
        </div>
    </div> -->
    <%= render 'layouts/notifications' %>
    <%= yield %>
    <footer>
        <p>@CopyRight Infratop.inc</p>
    </footer>
</body>

</html>

app/views/users/edit.html.erb
<div class="body-wrap">
    <div id="st-container" class="st-container">
        <div class="st-pusher">
            <div class="st-content">
                <div class="st-content-inner">
                    <section class="slice slice-lg sct-color-1">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-4 col-md-offset-4">
                                    <div class="form-user style-1 rounded has-shadow-1">
                                        <div class="form-header text-center">
                                            <h2 class="form-header-title">User info</h2>
                                        </div>
                                        <div class="form-body">
                                            <!-- ここにform_forを追加します -->
                                            <%= form_for(@user) do |f| %>
                                            <% if @user.errors.any? %>
                                            <% @user.errors.full_messages.each do |message| %>
                                            <h4>error prohibited this obj from being saved:</h4>
                                            <%= message %>
                                            <% end %>
                                            <% end %>
                                            <div class="form-group has-icon">
                                                <label class="control-label sr-only" for="inputEmail">name</label>
                                                <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder: "名前" %>
                                            </div>
                                            <div class="form-group has-icon">
                                                <div class="user-edit-image">
                                                    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %>
                                                </div>
                                                <label class="control-label sr-only" for="inputEmail">ProfileImage</label>
                                                <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
                                            </div>
                                            <%= f.text_area :introduction, autofocus: true, class:"form-control", id:"inputEmail", placeholder: "Introduction" %><br>
                                            <%= f.submit "Update User", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
                                            <% end %>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="container">
    <div class="row">
        <!-- ##javascriptで以下の1行を追加 -->
        <!-- <h1 class="jquery">Hello jQuery</h1> -->
        <div class="col-lg-4">
            <h1>User info</h1>
            <table class="table table-striped">
                <tr>
                    <%= attachment_image_tag current_user, :profile_image, :fill, 100,100, format: "jpeg", class: "pull-left profile-img", fallback: "no_image.jpg" %>
                </tr>
                <tr>
                    <td>name</td>
                    <td>
                        <%= current_user.name %>
                    </td>
                </tr>
                <tr>
                    <td>introduction</td>
                    <td>
                        <%= current_user.introduction %>
                    </td>
                </tr>
            </table>
            <%= link_to  edit_user_path(current_user.id), class: 'btn btn-default btn-block' do %>
            <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
            <% end %>
            <h1>New book</h1>
            <%= form_for(@book, url: books_path) do |f| %>
            <% if @book.errors.any? %>
            <div id="error_explanation">
                <ul>
                    <% @book.errors.full_messages.each do |message| %>
                    <li>
                        <%= message %>
                    </li>
                    <% end %>
                </ul>
            </div>
            <% end %>
            <ul>
                <li>
                    <h4>Title</h4>
                    <%= f.text_field :title, :size =>"44" %>
                </li>
                <li>
                    <h4> Opinion</h4>
                    <%= f.text_area :body, :cols =>"47", :rows => "1" %>
                </li>
                <br>
                <li>
                    <%= f.submit "Create Book", class: "btn btn-primary btn-block" %>
                </li>
                <% end %>
            </ul>
        </div>
        <div class="col-lg-8">
            <h1>Users</h1>
            <table class="table table-striped">
                <thread>
                    <tr>
                        <th>image</th>
                        <th>name</th>
                        <th colspan="2"></th>
                    </tr>
                </thread>
                <tbody>
                    <% @users.each do |user| %>
                    <tr>
                        <td>
                            <%= attachment_image_tag user, :profile_image, :fill, 50,50, format: "jpeg", class: "pull-left profile-img", fallback: "no_image.jpg", :width => "40", :height => "40" %>
                        </td>
                        <td>
                            <%= user.name %>
                        </td>
                        <td>
                            <%= link_to "show", user_path(user.id) %>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>
<%= paginate @users, class: "paginate" %>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-4">
            <h1>User info</h1>
            <table class="table table-striped">
                <tr>
                    <%= attachment_image_tag @user, :profile_image, :fill, 100,100, format: "jpeg", class: "pull-left profile-img", fallback: "no_image.jpg" %>
                </tr>
                <tr>
                    <td>name</td>
                    <td>
                        <%= @user.name %>
                    </td>
                </tr>
                <tr>
                    <td>introduction</td>
                    <td>
                        <%= @user.introduction %>
                    </td>
                </tr>
            </table>
            <% if @user == current_user %>
            <%= link_to  edit_user_path(current_user), class: 'btn btn-default btn-block' do %>
            <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
            <% end %>
            <% else %>
            <%= link_to  user_path(current_user), class: 'btn btn-default btn-block' do %>
            <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
            <% end %>
            <% end %>
            <h1>New book</h1>
            <%= form_for(@book, url: books_path) do |f| %>
            <% if @book.errors.any? %>
            <div id="error_explanation">
                <ul>
                    <% @book.errors.full_messages.each do |message| %>
                    <li>
                        <%= message %>
                    </li>
                    <% end %>
                </ul>
            </div>
            <% end %>
            <ul>
                <li>
                    <h4>Title</h4>
                    <%= f.text_field :title, :size =>"44" %>
                </li>
                <li>
                    <h4> Opinion</h4>
                    <%= f.text_area :body, :cols =>"47", :rows => "1" %>
                </li>
                <br>
                <li>
                    <%= f.submit "Create Book", class: "btn btn-primary btn-block" %>
                </li>
                <% end %>
            </ul>
        </div>
        <div class="col-lg-8">
            <h1>Books</h1>
            <table class="table table-striped">
                <thread>
                    <tr>
                        <th colspan="3"></th>
                        <th>Title</th>
                        <th>Opinion</th>
                    </tr>
                </thread>
                <tbody>
                    <% @books.each do |book| %>
                    <tr>
                        <td colspan="3">
                            <%= attachment_image_tag @user, :profile_image, :fill, 50,50, format: "jpeg", class: "pull-left profile-img", fallback: "no_image.jpg", :width => "40", :height => "40" %>
                        </td>
                        <td>
                            <%= link_to book.title, book_path(book.id) %>
                        </td>
                        <td>
                            <%= book.body %>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>
<%= paginate @books, class: "paginate" %>

app/views/users/top.html.erb
<div class="container1">
<h1>
	welcome to
	<span class="glyphicon glyphicon-book" aria-hidden="true"></span><<strong>Bookers !!</strong>
</h1>
<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span><<strong>Bookers,</strong><br>
you can share and exchange your opinionsm inpressions, and<br>
emotions<br>
about various books!</p>

 <div class="actions">
    <%= link_to "Log in",  "/users/sign_in", class: "btn btn-success" %>
     <%= link_to "Sign up",  "/users/sign_up", class: "btn btn-success" %>
  </div>
</div>